services:
  - type: web
    name: hrqdynasty-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn api_karma:app --host 0.0.0.0 --port 8000"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
